### ISSUE TITLE
Question On Aim TTi PL-P Series

### ISSUE THREAD

**Issue by Aamer-Hussaini** [sgoadhouse/dcps#3]
Hello

You've mentioned in the documentation that this library can be used to program the Aim TTi PL-P series. Could you please let me know which models you've used to test them on, as I am looking to purchase an Aim PL-P for remote-programmable power.

Also, generally, do I have to use this library or is there a command-line syntax which can allow control of Aim TTi PL-P power supplies? I've read in their Instruction Manual that command requests can be sent via USB interface as well.

I hope you could clarify the above for me!

Thank you

**Comment by sgoadhouse** [comment]
I no longer have easy access to that power supply, but it was one of the dual models. Looking at Aim TTi's current online offerings, it was probably a `PL303QMD-P` unless they had an earlier dual model like that with a different model number. I think the command set is universal between their `PL` units as long as you pick a `-P` version with programming support.

You do not *have* to use this library or any other library. There is not a command-line, per se, but there is a command syntax to sending queries and commands. You could simply send the commands as text to do what you want. However, at some point you may want to step output voltage using a for-loop and other such tasks where some sort of programming language make it easier and more flexible. I created this library slightly out of frustration because I was using a Rigol power supply and a colleague 6 timezones away had an Aim TTi PL-P power supply. I wanted to be able to write a set of tests that were universal. So I created this library to try to make a standardized API where the lower level code sent the appropriate commands based on the particular power supply used.

If you are getting started with controlling a power supply, I recommend working at the low level at first to get a feel for what you can do. There exist some basic programs that sort of give you a command line and you can type the commands and queries you want manually. Google should find something for you. However, after awhile you may appreciate the use of a library to take care of the lower levels tasks so you can focus on the higher level events.

**Comment by Aamer-Hussaini** [comment]
Thank you @sgoadhouse 

That gives me some confidence in investing into the tool 😀

On the ability to send queries and commands, how would you actually send these over a USB interface? Is there a separate application provided by the company, or can we use something native to Windows, like Pwsh or CMD?

For context, our use case is to remotely control this power supply to be able to automatically turn a connected device off/on. We are actually using an automation tool to interact with our desktop, thus, we do not want to rely on company provided software as the automation tool will find it difficult to interact with this and it will be much easier to use something native, like command-line.

I hope this is not a silly question -- I'm not really familiar with electronics very much!

**Comment by sgoadhouse** [comment]
You could use PyVISA directly. There is copious documentation including Installation and Use at [PyVISA](https://pyvisa.readthedocs.io/en/1.14.1/). Rigol has a tool that I believe they call UltraSigma you could try but Rigol may restrict its use to Rigol products. Aim TTi may have such a software tool if you dig around their website. You can also try googling "SCPI command tool".

**Comment by Aamer-Hussaini** [comment]
[like]  Aamer Hussaini reacted to your message:
________________________________
